[package]
name = "plast"
version = "0.0.3"
edition = "2024"

[lib]
name = "plast"
path = "src/lib.rs"

[[bench]]
name = "data_pipeline_benches"
harness = false

[dependencies]
bytemuck = "1.25.0"
crossbeam-channel = "0.5.15"
memmap2 = "0.9.10"
# Rayon, lazy processing, and fast string conversions are fully encapsulated here
polars = { version = "0.54.2", features = ["lazy", "strings", "ipc", "parquet", "ipc_streaming", "performant", "json", "csv"] }
rayon = "1.12.0"
tokenizers = "0.23.1"
thiserror = "2.0.18"
log = "0.4.32"
bytes = "1.12.1"

[dev-dependencies]
criterion = "0.8.2"
cudarc = { version = "0.19.8", features = ["cuda-12090"] }
env_logger = "0.11.10"
tempfile = "3.27.0"

[profile.bench]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"

[profile.dev.package."*"]
opt-level = 2
